### ISSUE TITLE
Plugin not showing icons

### ISSUE THREAD

**Issue by lajish** [paginagmbh/redmine_emojibutton#1]
Hi there,

I installed this plugin. Please check screenshot below. Redmine version 2.5.2

![image](https://cloud.githubusercontent.com/assets/6768694/3806519/77683cac-1c4e-11e4-81e0-ee5348f7bb8d.png)

If I inserts any emoticon in text field. The preview doesn't works. Google Chrome 36.0.1985.125

**Comment by tofi86** [comment]
Pinning the gemoji gem seems no longer to be necessary when using the latest gemoji gem 2.1.0 because they returned to bundle all icons with its name in addition to the unciode-named files like it was with 1.5.0.

Will release a new version of my plugin soo which comes with gemoji 2.1.0 support.
