### ISSUE TITLE
Root path is not not taken into account in the javascript and twice in the formatter

### ISSUE THREAD

**Issue by AThomsen** [paginagmbh/redmine_emojibutton#10]
In the `js` the root path is not taken into account:

    ...src="/images/emoji/'+valIcon+'.png" alt="...

and in `emojibutton_formatter.rb` it is twice!

     '<img alt="' + $1 + '" height="20" src="'+ Setting.protocol + "://" + Setting.host_name + Redmine::Utils.relative_url_root + '/images/emoji/' + $1 + '.png" style="vertical-align:middle" width="20" title=":' + $1 + ':" class="emoji" />'

You can remove `Redmine::Utils.relative_url_root` as `Setting.host_name` provides this as well.

**Comment by tofi86** [comment]
First one isn't easy as it's javascript and it can't read the rails config settings... Will see what I can do about it...

Second was introduced by f53dd2fc17ab15797acd5d56ea649b0aefbd5e0e. But you're right, it's doubled...

**Comment by AThomsen** [comment]
I know. I tried creating a .js.erb but couldn't make it work properly so I just ended up hardcoding it in the js :)

**Comment by tofi86** [comment]
Please test the bugfix in branch `bugfix/10` (733ab912732acadba6a3fc9397712d2c0d35fa3a).
Works for me (without a relative root path)

**Comment by AThomsen** [comment]
Clever fix :-)

It now works!
