### ISSUE TITLE
Missing images with release 0.4

### ISSUE THREAD

**Issue by alexandermeindl** [paginagmbh/redmine_emojibutton#13]
With release 0.4 I got a lot of 404 errors, if I use the emoji popup:

<img width="620" alt="emoji-popup" src="https://cloud.githubusercontent.com/assets/205221/11455649/6de69750-9669-11e5-967c-c67f7696e1f6.png">

After running 

 rake emoji

if can see a directory in public/images/emoji with this content:

<pre>
bowtie.png
feelsgood.png
finnadie.png
fu.png
goberserk.png
godmode.png
hurtrealbad.png
metal.png
neckbeard.png
octocat.png
rage1.png
rage2.png
rage3.png
rage4.png
shipit.png
suspect.png
trollface.png
unicode
</pre>

The plugin uses, e.g. "/images/emoji/hushed.png", but this file does not exist in my directory.

I removed the old directories public/images/emoji and public/plugin_assets/redmine_emojibutton and run a new installation.

**Comment by tofi86** [comment]
Did you follow the update instructions from README and ran `bundle update`?

What does `bundle show` print when running from plugin directory?

Where did you run `rake emoji`? In plugin dir or redmine root dir?

What Redmine version are you running?

**Comment by alexandermeindl** [comment]
*Did you follow the update instructions from README and ran bundle update?*
Yes, I did

*What does bundle show print when running from plugin directory?*
<pre>
Gems included by the bundle:
  * bundler (1.10.6)
  * gemoji (2.1.0)
</pre>

*Where did you run rake emoji? In plugin dir or redmine root dir?*
 In Redmine root directory.

*What Redmine version are you running?*
<pre>
Redmine version                3.1.2.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
</pre>

**Comment by tofi86** [comment]
Darn it! You're right.

This isn't a problem when updating from previous versions, its a problem when installing from scratch...

Why for heavens sake did they remove the named emoji images?! :angry: 

Will have to revert to the previous version of the plugin... Or finally pull in PR #3 which I don't like as I would have to maintain a name<->url mapping for the emoji files... :cry:

**Comment by tofi86** [comment]
released version 0.4.1 which fixes* this issue.

* means: reverts changes from 0.4.0 (43573337cfbf718676db0e7f0d7116439a18e020)
