### ISSUE TITLE
emoji button on Redmine 3.2.1

### ISSUE THREAD

**Issue by 3webbg** [paginagmbh/redmine_emojibutton#14]
Not displayed :)

![screen shot 2016-04-06 at 7 24 50 pm](https://cloud.githubusercontent.com/assets/2690892/14324412/5511fb78-fc2d-11e5-999c-6c713da38703.png)

**Comment by tofi86** [comment]
seems as if images are missing. did you follow the install instructions to the point?

Did you run `rake emoji` from the redmine root directory?
Is there a new folder `${redmine_root}/public/images/emoji/` with all the images?

**Comment by tofi86** [comment]
I'm closing this because @3webbg never answered my questions.
Feel free to reopen if needed.
