### ISSUE TITLE
Incompatibility with "A common libs"

### ISSUE THREAD

**Issue by marceldeglau** [paginagmbh/redmine_emojibutton#15]
Hello.

It seems Emojibutton is incompatible with the redmine plugin [A common libs](https://www.redmine.org/plugins/a_common_libs) from RMplus.pro Team.

If I've try to install both plugins I get the following trace when I try to migrate 
(`rake redmine:plugins:migrate RAILS_ENV=production --trace`):

`rake aborted!`
`SystemStackError: stack level too deep`
`/var/lib/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:244`

Is there a known issue, and are there any way to fix it?

Thanks for your support.

Kind regards

Marcel

**Comment by tofi86** [comment]
see issue #7 
It doesn't seem to be an issue with other plugins...

**Comment by tofi86** [comment]
Closing this. Feel free to reopen if the problem still exists.
