### ISSUE TITLE
Optimize emoji dialog box

### ISSUE THREAD

**Issue by jared-gs** [paginagmbh/redmine_emojibutton#18]
When a user opens the emoji display box, the browser downloads each emoji image individually from the host. This process has a lot of overhead, taking around ~4-8 seconds for all the images to completely load. Would it be possible to optimized this by having the dialog box load a single, monolithic image, which contains every emoji rather than hundred of small images? 

Having all emojis in a single image is how the "emoji cheat sheet" optimizes their site:

* http://www.webpagefx.com/tools/emoji-cheat-sheet/
* http://www.webpagefx.com/tools/emoji-cheat-sheet/graphics/sprite_8f7293ea485e190c9b4e31d516dbfea8.png

**Comment by tofi86** [comment]
Yeah, this is a bit annoying, you're right... :-/
However, every modern browser caches the icons after the first loading and doesn't fetch them a second/third time...

PullRequests are welcome for changes to this!

Also I was considering to switch to another emoji library (https://github.com/jonathanwiesel/gemojione) as the current one cannot be used in newer versions (see #3 / #13).

So this will probably take some time. Both of the issues...

**Comment by tofi86** [comment]
> Also I was considering to switch to another emoji library (https://github.com/jonathanwiesel/gemojione) as the current one cannot be used in newer versions (see #3 / #13).

Blocker:
* https://github.com/jonathanwiesel/gemojione/pull/44
  * without this, we cannot create the emoji selection panel
* https://github.com/jonathanwiesel/gemojione/pull/38
  * without this, we cannot replace widely used `:+1:` with its 👍 emoji

**Comment by tofi86** [comment]
> Blocker:
> 
> * jonathanwiesel/gemojione#44
>   * without this, we cannot create the emoji selection panel
> * jonathanwiesel/gemojione#38
>   * without this, we cannot replace widely used `:+1:` with its 👍 emoji

Those have been resolved with latest gemojione version 3.3: https://github.com/jonathanwiesel/gemojione/releases/tag/v3.3.0

I will try to work on it in the next couple of weeks...

**Comment by tofi86** [comment]
If you would like faster view in the emoji selector popup, please use the version 0.6.0 pre-release with support for native Unicode emojis displayed in your system emoji font. It can be accessed from the branch `gemoji-4.0-native-emojis-no-images`.
