### ISSUE TITLE
emojis are not appearing in redmine 3.4.3

### ISSUE THREAD

**Issue by chmich** [paginagmbh/redmine_emojibutton#19]
Hi, 

i installed this nice plugin in 2 Redmines:
3.4.2 => worked fine

then

3.4.3
=> no emojis appearing only blue question-marks, like screenshot below

then, i ran 

1. "bundle update" (in plugins-folder) 
2. rake emoji (in project-root)
3. restartet redmine
=> same result

what may be?

![emoji](https://user-images.githubusercontent.com/31048265/34447940-26009c32-ece9-11e7-9636-0678f74b3ab4.png)

**Comment by tofi86** [comment]
What URL does your browser show for an emoji image (blue question mark) when you right click and select "Show image"?

Did you try to refresh your browser with a clean cache for your redmine website? (e.g. Firefox Ctrl+Shift+R)

**Comment by chmich** [comment]
hi tofi,


right-click + show image in new tab:
URL:
<redmine-root>/images/emoji/sweat_drops.png

RESULT:
Forbidden
You don't have permission to access /images/emoji/heartbeat.png on this server.
-
i wanted to run 'rails routes', but it doesnt work (Error: Command 'routes' not recognized)
i checked the path, but it exits and permissions (-rw-r--r--) are given on the images

**Comment by chmich** [comment]
the error-message a second time:
in the last line is showed port 80 - why?
the system is only available by ssl.

Forbidden
You don't have permission to access /images/emoji/neckbeard.png on this server.
Apache/2.4.25 (Debian) Server at tmp2.sedlmair.ch Port 80

in the other redmine (runs on the same server) i can open a single emoji by mouse-right-click, with ssl

yes, i've cleared history and refresh-browser.

**Comment by tofi86** [comment]
Hi Christian,

I think it's a permission problem on your second redmine instance `tmp2.sedlmair.ch` as the images are all in the right place and you followed the installation instructions to the point.
Can you make sure that the `public/` directory, the `public/images/` and the `public/images/emoji/` directories have the correct permissions for your redmine webserver user?
You can compare the settings with your other redmine instance...

**Comment by tofi86** [comment]
By the way: when I try to open the URL `https://tmp2.sedlmair.ch/images/emoji/sweat_drops.png` the emoji image is perfectly shown! :)

**Comment by chmich** [comment]
yes, by this https://tmp2. ... it works - for me also.
i think the above message we can ignore, because it may be caused by the right-click-action. he wanted to call the image by port 80, and i had no forward to 443.

But, this tells us, that the permissions are working.

i made a test on google-chrome:
(chrome is newly installed)
same result: the first redmine runs, the "tmp2.sed.." delievers this ...

![chrome](https://user-images.githubusercontent.com/31048265/34458027-d46d6126-edc3-11e7-9e9f-4fc3d020f19d.png)

**Comment by tofi86** [comment]
Can you probably give me a test account or change the permission settings on tmp2 instance so that anonymous users can create tickets (and insert emojis)?

If not, please have a look in the source code of the emoji picker dialog by right-clicking in Chrome browser on one of the broken image icons and select "Inspect" ("Untersuchen").
Can you make sure that the highlighted `<img src="https://tmp2...."/>` has the right source URL in the `src` attribute? Can you please paste the URL here?

**Comment by chmich** [comment]
Hi tofi, a happy new year!
i wasnt able to copy the content of inspect-element to clipboard, but i assume the error is visible in this screenshot.

The emojibutton would like to call the emojis over http://... . This could'nt work because i had no redirect installed from http to https. I'm doing this this days and it will work!
BUT:
on my other Redmine, when i inspect the same element, the same calls are in "https://" and this logically works.

Best Regards,
Christian

![emoji](https://user-images.githubusercontent.com/31048265/34483919-bf0d3450-efc1-11e7-9d4a-10b374aeb175.png)

**Comment by tofi86** [comment]
thanks for the information.

In Redmine Admin Settings you have to change the Protocol from `http` to `https` then it should work.

**Comment by chmich** [comment]
Thanks tofi, this was a easy soulution!
Now it works fine.
Best Regards, thank you for the quick help and a happy new Year!
Christian

**Comment by tofi86** [comment]
Glad I could help.
Best, Tobias
