### ISSUE TITLE
problem with intallation emoji

### ISSUE THREAD

**Issue by vdvas** [paginagmbh/redmine_emojibutton#20]
When i use command rake emoji, i get error

root@debian:/usr/local/share/redmine-test# rake emoji
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["production"]
/usr/local/share/redmine-test/config/environment.rb:14:in `<top (required)>'
/usr/local/share/redmine-test/plugins/a_common_libs/lib/tasks/a_common_libs.rake:1:in `<top (required)>'
/usr/local/share/redmine-test/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/usr/local/share/redmine-test/lib/tasks/redmine.rake:186:in `each'
/usr/local/share/redmine-test/lib/tasks/redmine.rake:186:in `<top (required)>'
/usr/local/share/redmine-test/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)

In emoji window all smile are no pictures, only text.

**Comment by tofi86** [comment]
Did you run `bundle install` from the plugin directory before?

If so, try next with:

```
rake emoji  RAILS_ENV=production
```

**Comment by vdvas** [comment]
Yes. I run `bundle install` in plugin directory
I run  `rake emoji RAILS_ENV=production` from the redmine root dir.
It create folder and copy many pictures.
root@debian:/usr/local/share/redmine-test# rake emoji RAILS_ENV=production
mkdir -p /usr/local/share/redmine-test/public/images/emoji
cp /usr/local/lib/ruby/gems/2.3.0/gems/gemoji-1.5.0/images/emoji/oncoming_police_car.png /usr/local/share/redmine-test/public/images/emoji/
cp /usr/local/lib/ruby/gems/2.3.0/gems/gemoji-1.5.0/images/emoji/small_red_triangle_down.png /usr/local/share/redmine-test/public/images/emoji/

But in emoji window all smile are no pictures, only text.
Maybe I need reboot redmine service?

**Comment by tofi86** [comment]
Did you use the `master` branch?

Yes, please reboot the redmine webserver.

**Comment by vdvas** [comment]
> Did you use the master branch?
I dont know.
In /var/log/apache2/error.log
[Tue Feb 06 11:45:51 2018] [error] [client 192.168.10.26] File does not exist: /var/www/images, referer: http://redmine/redmine-test/boards/6/topics/120?r=164
The folder of emoji png is
/var/www/redmine-test/images/emoji
root@debian:~# ls /var/www -l
lrwxrwxrwx 1 root     root       37 Мар 15  2017 redmine-test -> /usr/local/share/redmine-test/public/

**Comment by tofi86** [comment]
you shouldn't install with a symlink in two directories.
I'm sorry but I cannot help you with that special symlink installation.

**Comment by vdvas** [comment]
This comand resolve problem
cp -r /usr/local/share/redmine-test/public/images/ /var/www/images
