### ISSUE TITLE
Feature: Support for Markdown formatter

### ISSUE THREAD

**Issue by stephenyeargin** [paginagmbh/redmine_emojibutton#4]
I've switched our Redmine to use Markdown (experimental) because I didn't like switching back and forth in markup languages between GitHub and Redmine. It appears that this is only loading the formatting rules in for Textile.

```ruby
Redmine::WikiFormatting::Textile::Formatter::RULES << :inline_emoji
```

My Redmine work usually involves the hooks, so I'm not as familiar with the internals. Not sure if 2.6 follows the same general rule where we could just add a line to cover both:

```ruby
Redmine::WikiFormatting::Textile::Formatter::RULES << :inline_emoji
Redmine::WikiFormatting::Markdown::Formatter::RULES << :inline_emoji
```

I'm putting this issue here instead of on @tmy/redmine_gemoji because it looks like yours is a bit further along and more recently maintained.

**Comment by tofi86** [comment]
confirmed. not as easy as it looks, but I'm working on it. see PR #5 (still work in progress)

**Comment by tofi86** [comment]
hey Stephen,
I fixed some errors in yesterdays first draft for markdown support. branch `markdown-support` now contains a first release candidate for emoji markdown support. It works well on my development machine :)
Any chance you could test this branch and send feedback?
Thanks!

**Comment by stephenyeargin** [comment]
I'll give it a spin.

**Comment by stephenyeargin** [comment]
![screen shot 2015-02-05 at 9 27 44 am](https://cloud.githubusercontent.com/assets/80459/6062950/4b3fa73a-ad19-11e4-844a-cfb86cecf465.png)

:shipit: Great work!

**Comment by tofi86** [comment]
Great, thanks for testing! :+1: :sunglasses:
