### ISSUE TITLE
Don't know how to build task 'emoji'

### ISSUE THREAD

**Issue by EricOVGU** [paginagmbh/redmine_emojibutton#6]
Hi there,

i have problems with installation of the emoji plugin. I checked out the repository in my redmine plugins folder. then i run 'bundle install' (but no new one was installed).
Next step (rake emoji) failed. I got this error:

```
rake aborted!
Don't know how to build task 'emoji'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/1.9.1/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/1.9.1/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

Please help me to find my failure!

**Comment by tofi86** [comment]
did you run `bundle install` *from within the plugin directory?*
Make sure to run it there in `${redmine_root}/plugins/redmine_emojibutton`

Then change back to `${redmine_root}` to run `rake emoji`

**Comment by EricOVGU** [comment]
I run bundle install within the plugin directory and rake emoji in the redmine root. I had try it again but the same error. Are there any requirements for this plugin (Ruby/Redmine Version)? Here are the information about my redmine:

 Redmine version                2.6.1.devel
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               PostgreSQL

Thank you for responding!

**Comment by tofi86** [comment]
> Are there any requirements for this plugin (Ruby/Redmine Version)?
Not as far as i know...

You could try to install manually from the redmine root:

```
gem install gemoji -v 1.5.0
```

However, I just see that you're running Rails 4.2. AFAIK this isn't supported for Redmine 2.6 => http://www.redmine.org/projects/redmine/wiki/RedmineInstall

**Comment by EricOVGU** [comment]
The gem is already installed. Maybe there is a problem with using the wrong rails version.
I think the ticket can be closed.
Thanks a lot for the help!

**Comment by EricOVGU** [comment]
Hello Tobias,
i have to ask another question. I still have problems with installation. I read in another ticket about the rake -T command. So I found out that there is no emoji task. Have you an idea why rake doesn´t recognize the emoji.rake file of your plugin?
Thanks a lot!
Eric

P.S. still using Rails 4.2 but now redmine 3.0.

**Comment by tofi86** [comment]
Well, I never experienced this by myself. The actual rake task is provided by the gem, not me.

I'd assume, the task is absent if the gem isn't installed. I've no other conclusion to that...

Can you please post the output of the following commands:

**From redmine root directory:**
```
gem list
bundle show
```

Then change to the **redmine_emojibutton directory:**
```
cd plugins/redmine_emojibutton/
bundle install
bundle show
rake emoji
```

**Comment by EricOVGU** [comment]
gem list (root):
*** LOCAL GEMS ***

actionmailer (4.2.0)
actionpack (4.2.0)
actionpack-action_caching (1.1.1)
actionpack-xml_parser (1.0.1)
actionview (4.2.0)
activejob (4.2.0)
activemodel (4.2.0)
activerecord (4.2.0)
activesupport (4.2.0)
arel (6.0.0)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.8.2)
capybara (2.4.4)
childprocess (0.5.5)
coderay (1.1.0)
docile (1.1.5)
erubis (2.7.0)
ffi (1.9.6)
gemoji (1.5.0)
globalid (0.3.3)
gravatar (1.0)
hike (1.2.3)
i18n (0.7.0)
io-console (0.4.2)
jquery-rails (3.1.2)
json (1.8.2, 1.8.1)
loofah (2.0.1)
mail (2.6.3)
metaclass (0.0.4)
mime-types (2.4.3)
mini_portile (0.6.2)
minitest (5.5.1, 4.7.5)
mocha (1.1.0)
multi_json (1.10.1)
net-ldap (0.3.1)
nokogiri (1.6.6.2)
pg (0.17.1)
protected_attributes (1.0.8)
psych (2.0.5)
rack (1.6.0, 1.5.2)
rack-openid (1.4.2)
rack-test (0.6.3)
rails (4.2.0)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.5)
rails-html-sanitizer (1.0.1)
railties (4.2.0)
rake (10.4.2, 10.1.0)
rbpdf (1.18.5)
rdoc (4.2.0, 4.1.0)
redcarpet (3.1.2)
request_store (1.0.5)
rmagick (2.13.4)
ruby-openid (2.3.0)
rubyzip (1.1.7)
selenium-webdriver (2.44.0)
simplecov (0.9.2)
simplecov-html (0.9.0)
sprockets (2.12.3)
sprockets-rails (2.2.4)
test-unit (2.1.2.0)
thor (0.19.1)
thread_safe (0.3.4)
tilt (1.4.1)
tzinfo (1.2.2)
websocket (1.2.1)
xpath (2.0.0)
yard (0.8.7.6)

bundle show:
Gems included by the bundle:
  * actionmailer (4.2.0)
  * actionpack (4.2.0)
  * actionpack-action_caching (1.1.1)
  * actionpack-xml_parser (1.0.1)
  * actionview (4.2.0)
  * activejob (4.2.0)
  * activemodel (4.2.0)
  * activerecord (4.2.0)
  * activesupport (4.2.0)
  * arel (6.0.0)
  * builder (3.2.2)
  * bundler (1.8.2)
  * capybara (2.4.4)
  * childprocess (0.5.5)
  * coderay (1.1.0)
  * docile (1.1.5)
  * erubis (2.7.0)
  * ffi (1.9.6)
  * globalid (0.3.3)
  * hike (1.2.3)
  * i18n (0.7.0)
  * jquery-rails (3.1.2)
  * json (1.8.2)
  * loofah (2.0.1)
  * mail (2.6.3)
  * metaclass (0.0.4)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.5.1)
  * mocha (1.1.0)
  * multi_json (1.10.1)
  * net-ldap (0.3.1)
  * nokogiri (1.6.6.2)
  * pg (0.17.1)
  * protected_attributes (1.0.8)
  * rack (1.6.0)
  * rack-openid (1.4.2)
  * rack-test (0.6.3)
  * rails (4.2.0)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.5)
  * rails-html-sanitizer (1.0.1)
  * railties (4.2.0)
  * rake (10.4.2)
  * rbpdf (1.18.5)
  * rdoc (4.2.0)
  * redcarpet (3.1.2)
  * request_store (1.0.5)
  * rmagick (2.13.4)
  * ruby-openid (2.3.0)
  * rubyzip (1.1.7)
  * selenium-webdriver (2.44.0)
  * simplecov (0.9.2)
  * simplecov-html (0.9.0)
  * sprockets (2.12.3)
  * sprockets-rails (2.2.4)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * tzinfo (1.2.2)
  * websocket (1.2.1)
  * xpath (2.0.0)
  * yard (0.8.7.6)

In the plugin directory:
bundle install:
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using gemoji 1.5.0
Using bundler 1.8.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

bundle show:
Gems included by the bundle:
  * bundler (1.8.2)
  * gemoji (1.5.0)

rake emoji:
(in /usr/share/redmine)
rake aborted!
Don't know how to build task 'emoji'

(See full trace by running task with --trace)

rake emoji --trace:
(in /usr/share/redmine)
rake aborted!
Don't know how to build task 'emoji'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task_manager.rb:62:in `[]'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:149:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

I hope I didn´t forget anything.

**Comment by tofi86** [comment]
Thanks.

However, I'Ve no idea why the rake task fails...
I'll give it a try with Rails 4.2 and redmine 3.0.0 in the next couple of days to see whether this is related to rails 4.2 / redmine 3.0 and we need to update to a newer version of the `gemoji` gem.

Can you try the code from PullRequest #3 which adds support for newer gemoji gem version?
If so, please make sure to run `bundle update` after having installed this fork...

**Comment by EricOVGU** [comment]
I have made the changes from the pullrequest. After bundle update the gemoji gem was updated to version 2.1.0. But the error "Don't know how to build task 'emoji'" is still there. Also rake -T emoji has no output.
Thanks for helping me!

**Comment by tofi86** [comment]
Alright, thanks for testing... So I'm at a loss for the moment... Sorry... :disappointed:

**Comment by EricOVGU** [comment]
Thank you for trying to help me! Maybe we find a solution in time.

**Comment by EricOVGU** [comment]
A very big SORRY! I´ve find my failure. I used the wrong directory. I put new plugins in redmine/lib/plugins instead of redmine/plugins.
Now it works perfect. I´m new to redmine so please excuse.
Thanks for your time!

**Comment by tofi86** [comment]
:hushed: \*sigh*

**Comment by Nexword** [comment]
Hello! Can you help me, pls. I have same problem. I have directory **usr/share/redmine**. I created folder "plugins"  into and cloned into **usr/share/redmine/plugins** emoji plugin (git clone https://github.com/paginagmbh/redmine_emojibutton.git). 
In **usr/share/redmine/plugins/redmine_emojibutton/**
```
bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as
root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/..
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using gemoji 1.5.0
Using bundler 1.10.6 
```
In this directory:
```
bundle show
Gems included by the bundle:
  * bundler (1.10.6)
  * gemoji (1.5.0)
```
Next step, i wrote **rake emoji** into **usr/share/redmine**
```
rake emoji

rake aborted!
cannot load such file -- tasks/emoji.rake
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/share/redmine/plugins/redmine_emojibutton/lib/tasks/emoji.rake:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `block in <top (required)>'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `each'
/usr/share/redmine/lib/tasks/redmine.rake:126:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `block in load_tasks'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `each'
/usr/lib/ruby/vendor_ruby/rails/engine.rb:425:in `load_tasks'
/usr/lib/ruby/vendor_ruby/rails/application.rb:145:in `load_tasks'
/usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
/usr/share/redmine/Rakefile:7:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:589:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:89:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:88:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:72:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:70:in `run'
/usr/bin/rake:27:in `<main>'
```
What do you think about this error? What can go wrong?
```
Environment:
  Redmine version              2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_issue_control_panel    0.3.0
```
